version: '3'

services:
  database:
    image: "postgres"
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
  microservice:
    image: "jinilover/service-in-fp-scala:0.1"
    ports:
      - 9000:9000
    environment:
      # all env vars are defined in application.conf
      - DB_URL=jdbc:postgresql://database:5432/postgres
      - API_PORT=9000
    depends_on:
      - database